#!/usr/bin/env node
/**
 * Enable a scaffold capability in an ALREADY-GENERATED project.
 *
 * `init.mjs --minimal` prunes unpicked capabilities entirely; this tool brings
 * one back later. It fetches a PRISTINE scaffold copy (from the origin recorded
 * in .clevscaffold.json, or --from), copies the capability's libs/modules/
 * migrations in, re-adds tsconfig paths + package deps + root scripts + env
 * keys, and writes an exact wiring guide (docs/wiring-<capability>.md) for the
 * few lines that must be merged into files you may have edited (app.module.ts,
 * main.ts, …) — applying those is the only manual step. See docs/EVOLVING.md.
 *
 * Usage:
 *   node scripts/add.mjs <capability…> [--from <path|git-url>] [--ref <sha|branch>]
 *                        [--no-install]
 *   capabilities: auth · messaging · feature-flags · metrics · compliance
 *
 * Examples:
 *   node scripts/add.mjs messaging                      # fetch from recorded origin
 *   node scripts/add.mjs compliance --from ../ClevScaffold
 *
 * Zero dependencies. Idempotent: already-present capabilities are skipped.
 */
import { existsSync, cpSync, readFileSync, writeFileSync, appendFileSync, statSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import {
  readJson,
  writeJson,
  stripSentinelBlocks,
  stripSentinelMarkers,
  extractSentinelBlocks,
  fetchPristine,
} from './scaffold-manifest.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ALIASES = { 'feature-flags': 'featureflags' };

function parseArgs(argv) {
  const out = { caps: [], opts: {}, flags: new Set() };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--no-install') out.flags.add('no-install');
    else if (a.startsWith('--')) out.opts[a.slice(2)] = argv[++i];
    else out.caps.push(ALIASES[a] ?? a);
  }
  return out;
}

/** Copy src (file or dir) from pristine into the project, skipping artifacts. */
function copyIn(pristine, rel) {
  const src = path.join(pristine, rel);
  const dest = path.join(ROOT, rel);
  if (!existsSync(src)) return false;
  cpSync(src, dest, {
    recursive: true,
    filter: (s) =>
      !['node_modules', 'dist', 'coverage', '.expo', '.next'].includes(path.basename(s)),
  });
  console.log(`  copied ${rel}`);
  return true;
}

/** A capability path applies only if its owning app exists in this project. */
function appliesLocally(rel) {
  const m = rel.match(/^(apps\/[^/]+)\//);
  return m ? existsSync(path.join(ROOT, m[1])) : true;
}

async function main() {
  const { caps: requested, opts, flags } = parseArgs(process.argv.slice(2));
  if (requested.length === 0) {
    console.error(
      'usage: node scripts/add.mjs <capability…> [--from <path|git-url>] [--ref <sha>] [--no-install]\n' +
        '  capabilities: auth · messaging · feature-flags · metrics · compliance',
    );
    process.exit(2);
  }
  if (existsSync(path.join(ROOT, 'scripts/init.mjs'))) {
    throw new Error(
      'this is the pristine scaffold — every capability is already present. add.mjs is for generated projects.',
    );
  }
  if (!existsSync(path.join(ROOT, '.clevscaffold.json'))) {
    throw new Error('.clevscaffold.json not found — was this project generated by init.mjs?');
  }
  const manifest = readJson(ROOT, '.clevscaffold.json');
  const present = new Set(manifest.capabilities ?? []);

  const { dir: pristine, cleanup } = fetchPristine(ROOT, opts.from, opts.ref, manifest);
  try {
    // The PRISTINE manifest is the source of truth for what a capability contains
    // (the local copy may predate newer capabilities).
    const pm = await import(
      pathToFileURL(path.join(pristine, 'scripts/scaffold-manifest.mjs')).href
    );
    const selectable = pm.ALL_CAPS.filter((c) => c !== 'tasks');

    for (const c of requested) {
      if (!selectable.includes(c)) {
        throw new Error(`unknown capability "${c}" — pick from: ${selectable.join(', ')}`);
      }
    }

    // Resolve the requires-closure (messaging/compliance imply auth), drop present.
    const wanted = new Set(requested);
    let grew = true;
    while (grew) {
      grew = false;
      for (const c of [...wanted]) {
        for (const r of pm.CAPABILITIES[c].requires ?? []) {
          if (!wanted.has(r) && !present.has(r)) {
            wanted.add(r);
            grew = true;
            console.log(`  note: ${c} requires ${r} — adding it too`);
          }
        }
      }
    }
    const adding = pm.ALL_CAPS.filter((c) => wanted.has(c) && !present.has(c));
    for (const c of requested) {
      if (present.has(c)) console.log(`  skip: ${c} is already enabled`);
    }
    if (adding.length === 0) {
      console.log('nothing to add.');
      return;
    }
    const hasTypeorm = existsSync(path.join(ROOT, 'libs/database'));
    for (const c of adding) {
      if ((pm.CAPABILITIES[c].dirs ?? []).length > 0 && !hasTypeorm) {
        throw new Error(
          `capability "${c}" is TypeORM-coupled and this project has no TypeORM app (libs/database missing)`,
        );
      }
    }

    console.log(`\nAdding: ${adding.join(', ')}\n`);
    const copiedRoots = [];

    for (const c of adding) {
      const cap = pm.CAPABILITIES[c];
      for (const d of cap.dirs ?? []) {
        if (!appliesLocally(d)) continue;
        if (existsSync(path.join(ROOT, d))) {
          console.log(`  skip: ${d} already exists`);
          continue;
        }
        if (copyIn(pristine, d)) copiedRoots.push(d);
      }
      for (const f of cap.files ?? []) {
        if (appliesLocally(f) && !existsSync(path.join(ROOT, f)) && copyIn(pristine, f))
          copiedRoots.push(f);
      }
      for (const m of cap.migrations ?? []) {
        const rel = `${pm.MIGRATIONS_DIR}/${m}`;
        if (existsSync(path.join(ROOT, pm.MIGRATIONS_DIR)) && copyIn(pristine, rel))
          copiedRoots.push(rel);
      }
    }

    // Copied files still carry `@clevrook` and sentinel blocks for capabilities
    // this project does NOT have — rename the scope, strip absent-cap blocks,
    // then remove the leftover marker lines.
    const absent = pm.ALL_CAPS.filter((c) => !present.has(c) && !wanted.has(c));
    for (const rootRel of copiedRoots) {
      const full = path.join(ROOT, rootRel);
      if (!existsSync(full)) continue;
      const files = statSync(full).isDirectory() ? pm.walkTextFiles(full) : [full];
      for (const file of files) {
        const rel = path.relative(ROOT, file);
        const text = readFileSync(file, 'utf8');
        if (text.includes(pm.OLD_SCOPE)) {
          writeFileSync(file, text.split(pm.OLD_SCOPE).join(manifest.scope));
        }
        for (const a of absent) stripSentinelBlocks(ROOT, rel, a);
        stripSentinelMarkers(ROOT, rel);
      }
    }

    // tsconfig paths + app package deps + root scripts (re-scoped to this project).
    const tsconfig = readJson(ROOT, 'tsconfig.base.json');
    const pristineTs = readJson(pristine, 'tsconfig.base.json');
    const rootPkg = readJson(ROOT, 'package.json');
    const pristinePkg = readJson(pristine, 'package.json');
    for (const c of adding) {
      const cap = pm.CAPABILITIES[c];
      for (const p of cap.tsPaths ?? []) {
        for (const key of [p, `${p}/*`]) {
          const val = pristineTs.compilerOptions?.paths?.[key];
          if (val) tsconfig.compilerOptions.paths[key.replace(pm.OLD_SCOPE, manifest.scope)] = val;
        }
      }
      for (const pd of cap.pkgDeps ?? []) {
        if (!existsSync(path.join(ROOT, pd.file))) continue;
        const appPkg = readJson(ROOT, pd.file);
        const dep = pd.dep.replace(pm.OLD_SCOPE, manifest.scope);
        appPkg.dependencies = { ...appPkg.dependencies, [dep]: '*' };
        appPkg.dependencies = Object.fromEntries(
          Object.entries(appPkg.dependencies).sort(([a], [b]) => a.localeCompare(b)),
        );
        writeJson(ROOT, pd.file, appPkg);
        console.log(`  added ${dep} to ${pd.file}`);
      }
      for (const s of cap.scripts ?? []) {
        if (pristinePkg.scripts?.[s] && !rootPkg.scripts?.[s]) {
          rootPkg.scripts[s] = pristinePkg.scripts[s];
          console.log(`  added root script ${s}`);
        }
      }
    }
    writeJson(ROOT, 'tsconfig.base.json', tsconfig);
    writeJson(ROOT, 'package.json', rootPkg);

    // .env.example — append the capability's env block (scope-agnostic).
    for (const c of adding) {
      const blocks = extractSentinelBlocks(pristine, '.env.example', c);
      if (blocks.length && existsSync(path.join(ROOT, '.env.example'))) {
        const local = readFileSync(path.join(ROOT, '.env.example'), 'utf8');
        const content = blocks.join('\n');
        const probe = content.split('\n').find((l) => /^[A-Z_]+=/.test(l));
        if (!probe || !local.includes(probe.split('=')[0])) {
          appendFileSync(
            path.join(ROOT, '.env.example'),
            `\n# ── added by scripts/add.mjs (${c}) ──\n${content}\n`,
          );
          console.log(`  appended ${c} env keys to .env.example`);
        }
      }
    }

    // Wiring guide for pre-existing files that were sentinel-stripped at init.
    // (Freshly copied files above already contain their wiring — nothing manual.)
    const copiedSet = new Set(copiedRoots);
    const wiringDocs = [];
    for (const c of adding) {
      const sections = [];
      for (const rel of pm.CAP_SENTINEL_FILES) {
        if (rel === '.env.example') continue; // handled automatically above
        if (!existsSync(path.join(ROOT, rel))) continue;
        if ([...copiedSet].some((r) => rel === r || rel.startsWith(`${r}/`))) continue;
        const blocks = extractSentinelBlocks(pristine, rel, c);
        if (blocks.length === 0) continue;
        const clean = blocks
          .map((b) =>
            b
              .split('\n')
              .filter((l) => !/clevscaffold:[a-z]+:(start|end)/.test(l))
              .join('\n')
              .split(pm.OLD_SCOPE)
              .join(manifest.scope),
          )
          .join('\n\n// … and, further down in the same file …\n\n');
        sections.push(`### \`${rel}\`\n\n\`\`\`ts\n${clean}\n\`\`\``);
      }
      if (sections.length === 0) continue;
      const doc = `# Wiring: enable \`${c}\`

Generated by \`scripts/add.mjs\` — the capability's code was copied in, but these
lines must be merged into files this project owns (they were pruned at init and
the files may have changed since). Placement mirrors the reference app in the
scaffold: imports go with the other imports; config namespaces into the
\`load: [...]\` array; modules into \`imports: [...]\`; providers into
\`providers: [...]\`. When in doubt, open the same file in the pristine scaffold
and mirror it.

${sections.join('\n\n')}

## After wiring

\`\`\`bash
npm install          # if not already run by add.mjs
npm run migration:run
npm run verify
\`\`\`

Delete this file once applied.
`;
      const docRel = `docs/wiring-${c}.md`;
      writeFileSync(path.join(ROOT, docRel), doc);
      wiringDocs.push(docRel);
      console.log(`  wrote ${docRel}`);
    }

    // Record the new state.
    manifest.capabilities = [...new Set([...present, ...adding])].sort();
    writeJson(ROOT, '.clevscaffold.json', manifest);

    if (!flags.has('no-install')) {
      console.log('\nInstalling dependencies…');
      execSync('npm install', { cwd: ROOT, stdio: 'inherit' });
    }

    console.log(`\n✅  added: ${adding.join(', ')}`);
    if (wiringDocs.length) {
      console.log(`\nNEXT (manual): apply the wiring guide${wiringDocs.length > 1 ? 's' : ''}:`);
      for (const d of wiringDocs) console.log(`  - ${d}`);
    }
    console.log('Then: npm run migration:run && npm run verify');
  } finally {
    cleanup();
  }
}

main().catch((err) => {
  console.error(`\n✗ add failed: ${err.message}`);
  process.exit(1);
});
